- src/ale_interface.cpp
- src/ale_interface.hpp
Tested the legacy constructor in the shared_library_interface_example and confirmed that it works as expected.
> Added legacy constructor to ale_interface.

- CMakeLists.txt
> Added CMake support!

- src/controllers/rlglue_controller.cpp
Fixes compile error. Verified that RLGlue experiment still runs.
> Updated rlglue controller to use new export screen.

- src/ale_interface.cpp
- src/common/display_screen.cpp
- src/environment/stella_environment.cpp
- src/environment/stella_environment.hpp
This PR adds simple action repeat stochasticity. Additionally it makes display_screen's manual control mode more realistic and fixes one bug with manual control in the ale_interface.
> We're Ready to Test Stochasticity

- src/common/Log.cpp
- src/common/Log.hpp
After commit 6a3e061 some files were missing [Log.hpp/cpp]. Taking them from the previous commit and renaming accordingly.
> Compilation problem: Missing files Log.hpp/cpp

- CMakeLists.txt
- src/ale_interface.cpp
- src/common/misc_tools.h
- src/emucore/Console.cxx
- src/main.cpp
- src/os_dependent/FSNodeWin32.cxx
- src/os_dependent/OSystemWin32.cxx
This fixes mingw/gcc compilation issues for me. Related ticket #78.
> Updated to fix compilation using mingw on Windows.

- ale_python_interface/ale_c_wrapper.cpp
- ale_python_interface/ale_c_wrapper.h
- ale_python_interface/ale_python_interface.py
- src/environment/ale_state.cpp
- src/environment/ale_state.hpp
This is on top of the new head of dev after master was merged into it. It also addressed the comments made in #106 and #83, and uses the Stella serializer/deserializer which I didn't know existed.
> Serialization of ALEStates to strings

- .travis.yml
- README.md
> Added @jleni's travis CI suggestion

- src/games/Roms.cpp
- src/games/module.mk
- src/games/supported/LaserGates.cpp
- src/games/supported/LaserGates.hpp
Laser Gates, ROM file `lasergates.bin`:
```
Cart Name:       Laser Gates (1983) (Imagic)
Cart MD5:        1fa58679d4a39052bd9db059e8cda4ad
```
> Add support for the game Laser Gates.

- README.md
- Readme.txt
This one also adds it to Readme.md
> quick compilation instructions

- CMakeLists.txt
- src/controllers/fifo_controller.cpp
A minor fix to the FIFO controller, which was causing a crash in the fifo example. Please LGTM @mhauskn or @mcmachado
> Added fifo example to CMakeLists; fixed a read bug in FIFO controller

- README.md
Incorporates information from the old ALE website, and improves formatting.
> New Readme file for the ALE

- CMakeLists.txt
- doc/examples/Makefile.sharedLibraryWithModes
- doc/examples/sharedLibraryInterfaceWithModesExample.cpp
- src/ale_interface.cpp
- src/ale_interface.hpp
- src/common/Constants.h
@mgbellemare, I created a first minimal pull request for this feature. In this first PR all I'm doing is defining types and the interface I want to make accessible for the end user. If you are ok with it, I'll proceed to implement the functionalities, to update the manual, and to implement the Python interface as well.
> Minimal definition of interfaces to support modes and difficulties.

- setup.py
- src/environment/stella_environment_wrapper.hpp
> Fix compilation errors when installing python interface

- setup.py
- src/environment/ale_state.cpp
This should take care of serialization with modes & difficulty. Also note the change to Python interface version.
> Fix modes serialization

- src/games/supported/DoubleDunk.cpp
- src/games/supported/DoubleDunk.hpp
The modes in DoubleDunk were wrong. This fixes it.
> Fixing bug in DoubleDunk modes.

- README.md
Now that we are close to releasing the new ALE version I also updated the README file with our latest paper introducing some of the features of the new ALE.
> Updating references.

- .travis.yml
This simplifies the toolchain selection.
> [travis] Updates the Travis-chosen Linux distribution.

- README.md
This allows easier editing and maintenance of the README file.
> [README] Reformat markdown sources

- src/emucore/TIA.cxx
- src/emucore/TIA.hxx
This is one of a handful of changes to Stella that will improve robustness of ALE which makes us diverge from the direction that mainline Stella has taken. In the event that we will update the Stella code, this change (and the related future changes) will be overwritten; upstream Stella is quite different. But for now, this is an improvement for us.
> [emucore/TIA] Improve const-correctness

- src/emucore/Settings.cxx
These will enable support for a wider set of ROMs
> [emucore/Settings] Declare additional settings

- src/ale_interface.cpp
- src/games/RomSettings.hpp
This hook allows ROMs to change the effective Stella emulator settings.
> [game/RomSettings, ale_interface] Add settings customization hook

- .github/workflows/build-ale-py.yml
- .github/workflows/build-ale.yml
- .github/workflows/release-ale-py.yml
Fixes some checkout issues from https://github.com/actions/checkout/issues/23.
> Bump Github Actions actions/checkout to v2

- md5.txt
Closes issue #345 in the manner agreed upon in the discussion.
> Remove duplicate roadrunner md5

- src/common/VideoModeList.hxx
- src/emucore/Settings.cxx
Two minor tweaks, backported from internal changes.
> Minor tweaks

- src/emucore/Console.cxx
- src/emucore/OSystem.cxx
- src/emucore/OSystem.hxx
- src/emucore/Settings.cxx
- src/emucore/bspf/bspf.hxx
- src/os_dependent/OSystemUNIX.cxx
This just removes pieces of Stella that were commented out. Most of the comments have to do with Stella's GUI interface.
This info can be queried from git if need be.
> Remove leftovers from Stella

- src/emucore/CartUA.cxx
See upstream: https://github.com/stella-emu/stella/commit/79e4e42ae755eb77994b88c3173df1babd01185f#diff-b826c30b083db909de2492a92e68832b4a9f169307b65271cea40a6f8182eb27R182
> Fix address for patching bankswitch type UA

- src/python/__init__.py
- src/python/gym/__init__.py
- src/python/gym/environment.py
- src/python/gym/utils.py
- src/python/roms/utils.py
- tests/python/gym/test_gym_interface.py
Registers `ALE/{GAME]-v5` environments with Gym. The v5 environments follow the recommended methodologies outlined in revisiting the ALE.
> Register Gym v5 environments

- CHANGELOG.md
- src/ale_interface.cpp
- src/ale_interface.hpp
- src/environment/stella_environment.cpp
- src/environment/stella_environment.hpp
- src/python/ale_python_interface.hpp
- tests/python/test_python_interface.py
Upstreaming a PR from our project: https://github.com/PettingZoo-Team/Multi-Agent-ALE/pull/8. Similar PRs have been proposed before:  mgbellemare#247, mgbellemare#232,  but were not merged due to inactivity. 
Seems to be about time this change is actually merged with the main project.
> Added setRAM function.

- examples/python-rom-package/README.md
- src/python/gym.py
- src/python/roms/__init__.py
- src/python/roms/utils.py
> Lazy load ROMs via plugins

- src/python/gymnasium.py
Add a Gymnasium based environment as an alternative to Gym
> Add Gymnasium support

- src/python/roms/__init__.py
Update the loading of ROMs to support loading from a system variable for organisations that don't use pip, i.e., google
> Add option for loading ROMs from system environment variable

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/wheels.yml
The windows and macos CI is failing, trying to update the CI versions to see if that does anything
> Update CI (re-enable windows and pin macos)

- src/CMakeLists.txt
> remove cmake module path from configure_package_config_file

- README.md
> Update docs to fix broken `loadROM`

- scripts/download_unpack_roms.sh
To check that the ROMs download hasn't changed then we check sha256 of the file along with sha's of the individual ROM files
> ROM download SHA256 testing

- src/ale/common/Constants.cpp
> Removing GPL-3.0 license reference

- src/ale/python/ale_python_interface.hpp
More info can be found here: https://github.com/Farama-Foundation/Arcade-Learning-Environment/issues/594#issuecomment-2657614718
> Fix for Python single-argument act resulting in no-op (#594)

- scripts/benchmark-vec-env.py
- src/ale/python/vector_env.py
To help with benchmarking the performance of optimisations for the AtariVectorEnv. 
This PR implements a logging and plotting of vector environment performances
> Add `AtariVectorEnv` benchmarking

- src/ale/python/__init__.py
Fixes https://github.com/Farama-Foundation/Arcade-Learning-Environment/issues/630
> Remove Gymnasium as dependency
