doc/examples/sharedLibraryInterfaceExample.cpp, src/ale_interface.cpp, src/ale_interface.hpp, src/common/export_screen.cpp, src/common/export_screen.h, src/emucore/OSystem.cxx, src/environment/stella_environment.cpp, src/environment/stella_environment.hpp
Updated export screen to save ALEScreen screens rather than IntMatrix screens. Removed dependencies on OSystem from constructor. Added convenience methods to ALEInterface and StellaEnvironment to allow easy saving of the current screen. Hopefully this should take us closer to being able to make videos. One issue that remains is that the saved screens have resolution 160x210...
=> Refactored Export Screen

src/agents/PlayerAgent.hpp, src/games/RomSettings.cpp, src/games/RomSettings.hpp
This PR corrects an issue in which ALE would not update the set of legal & minimal actions if a second rom was loaded.  
Example of Problem (using C++ Interface): 
```c++ 
ale.loadROM("skiing.bin");
ActionVect legal_actions = ale.getLegalActionSet();
for (int i=0; i<legal_actions.size(); ++i) {
cout << legal_actions[i] << ", ";
}
cout << endl;
ale.loadROM("space_invaders.bin");
legal_actions = ale.getLegalActionSet();
for (int i=0; i<legal_actions.size(); ++i) {
cout << legal_actions[i] << ", ";
}
cout << endl;
```
Correct Output:
```
Game console created:
ROM file:  /u/mhauskn/projects/ale-assets/roms/skiing.bin
...
0, 2, 3, 4, 5, 6, 7, 8, 9, 
Game console created:
ROM file:  /u/mhauskn/projects/ale-assets/roms/space_invaders.bin
...
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
```
=> Refactored RomSettings to remove the ActionVects.

doc/examples/videoRecordingExample.cpp, src/common/SoundExporter.cpp, src/common/SoundExporter.hpp, src/common/SoundNull.hxx, src/common/SoundSDL.cxx, src/common/SoundSDL.hxx, src/common/display_screen.cpp, src/emucore/Sound.hxx, src/environment/stella_environment.cpp
Fixed synchronization issues with sound recording. I had it wrong all along. The current fix is only a 
90% solution. It still requires the SDL display to be running at the right speed. As a result the sound isn't quite as good as it should be. A better solution is to emulate the TIA/sound buffer, i.e. replicate the code
inside SoundSDL and TIASnd to avoid real-time constraints. This will have to wait until ALE 0.6.
=> Dev video recording fix

ale_python_interface/ale_c_wrapper.h, ale_python_interface/ale_python_interface.py
The existing version of getScreenRGB returns a length 33600 numpy array of 32-bit integers, where the three color channels are embedded as 8-bit fields inside the integer values.  This requires the user to know the bitwise layout of the color channels and write Python code to extract the individual color values. 
This pull request modifies the Python interface so that getScreenRGB returns a height x width x 3 numpy array of type uint8, where each entry represents a single color value in the range 0-255.
=> Fix Python getScreenRGB to split color channels.

src/ale_interface.cpp
When you try to, for example, get the number of lives left before loading the ROM, the code should now throw a std::runtime_error.
Optionally, you could also write to a log and mention that this has occurred. 
Seems superfluous - the user will see the exception. 
Optionally, you could move that pointer check into another function to avoid repeating code. 
Also seems a little unnecessary at this point, but I can see the merits.
=> Throw exception instead of segfaulting on attempt to acess ROM data before ROM set.

src/ale_interface.hpp
A header was missing and I could not build anymore.
=> error: ‘runtime_error’ is not a member of ‘std’

src/games/Roms.cpp, src/games/module.mk, src/games/supported/Tetris.cpp, src/games/supported/Tetris.hpp
I've added two changes I was missing (whem moving from master to dev)
hope it is working now.
=> Tetris support

ale_python_interface/ale_c_wrapper.h, ale_python_interface/ale_python_interface.py
Tested that clone/restore works correctly on Ubuntu. Not sure how to verify the integrity of RNG serialization, but if it's working in the ALE_inteface, it'll be working in the python as well.
=> Added clone/restore state methods to ale_python_interface.

setup.py
The python interface doesn't have a version number. The current default value is 0.0.0
pip doesn't upgrade and it has to be forced through --upgrade. In addition, it is not clear which version is being used.
I am not sure how you would like to treat version numbers so I am temporarily adding version=0.0.1
=> Adding a version number to the python interface

src/games/supported/Breakout.cpp, src/games/supported/Pong.cpp
Hi,
I've been using Nathan Sprague's implementation (deep_q_rl) and I have struggled to achieve results that are consistent with DQN (Deepmind).
I recently noticed that ALE is different from Xitari in several games. In particular, Breakout and Pong declare a different set of minimal actions.
In this PR, I am removing some spurious actions only in Breakout/Pong in order to match Xitari.
I've seen some differences in other games. Maybe you can comment on that. Should we fix those too? Are Atlantis/Frostbite better?
|Game|ALE|Xitari|
|---|---|---|
|Asteroids| | Score wrapping|
|Atlantis|Seems newer/better||
|Breakout|6 actions|4 actions|
|Frostbite|Seems newer/better||
|Kangaroo||Score is taken from different memory regions|
|Pong|6 actions|3 actions|
|Space Invaders|Score wrapping||
|Wizard …
=> MinimalActions - Breakout / Pong

src/games/Roms.cpp, src/games/module.mk, src/games/supported/Turmoil.cpp, src/games/supported/Turmoil.hpp
This adds support for the game Turmoil.
`stella -rominfo turmoil.bin` shows:
```
Cart Name:       Turmoil (1982) (20th Century Fox)
Cart MD5:        7a5463545dfb2dcfdafa6074b2f2c15e
```
I tested this game using my [Julia wrapper for ALE](https://github.com/nowozin/ArcadeLearningEnvironment.jl) and rewards/scores and lives agree with screenshot values over a large number of random games.
=> Add support for the game Turmoil.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/Koolaid.cpp, src/games/supported/Koolaid.hpp
Add support for the game _Kool Aid Man_, using the ROM name `koolaid.bin`.
```
Cart Name:       Kool-Aid Man (1983) (M Network)
Cart MD5:        534e23210dd1993c828d944c6ac4d9fb
```
=> Add support for the game Koolaid.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/MrDo.cpp, src/games/supported/MrDo.hpp
This game is actually quite fun, and the popular PC game [_Digger_](https://en.wikipedia.org/wiki/Digger_%28video_game%29) is a clone of Mr. Do.
```
Cart Name:       Mr. Do! (1983) (Coleco)
Cart MD5:        0164f26f6b38a34208cd4a2d0212afc3
Bankswitch Type: F8* (8K) 
```
I verified that scores/lives are agreeing with screenshots over many random plays.
=> Add support for the game Mr. Do.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/DonkeyKong.cpp, src/games/supported/DonkeyKong.hpp
```
Cart Name:       Donkey Kong (1987) (Atari)
Cart MD5:        36b20c427975760cb9cf4a47e41369e4
```
I minimally tested the game with a random policy, however the game did not complete a level using a random policy.  I am pretty confident the support is solid.
=> Add support for the game Donkey Kong.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/KeystoneKapers.cpp, src/games/supported/KeystoneKapers.hpp
ROM file `keystonekapers.bin`:
```
Cart Name:       Keystone Kapers (1983) (Activision)
Cart MD5:        be929419902e21bd7830a7a7d746195d
```
Limited testing on random policy agrees with lives and scores.  (This game is difficult for a random policy.)
=> Add support for the game Keystone Kapers.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/Trondead.cpp, src/games/supported/Trondead.hpp
Support for Tron Deadly Discs, file name `trondead.bin`:
```
Cart Name:       TRON - Deadly Discs (1982) (M Network)
Cart MD5:        fb27afe896e7c928089307b32e5642ee
```
I tested that the reported lives/scores agree with screenshots on many playouts.
=> Add support for the game Tron Deadly Discs.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/Frogger.cpp, src/games/supported/Frogger.hpp
Full support for the game Frogger.  The ROM file `frogger.bin` has the following information:
```
Cart Name:       Frogger (1982) (Parker Bros)
Cart MD5:        081e2c114c9c20b61acf25fc95c71bf4
```
=> Add support for the game Frogger.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/SirLancelot.cpp, src/games/supported/SirLancelot.hpp
Sir Lancelot, ROM file `sirlancelot.bin`:
```
Cart Name:       Sir Lancelot (1983) (Xonox) [a1]
Cart MD5:        7ead257e8b5a44cac538f5f54c7a0023
Bankswitch Type: F8* (8K) 
```
=> Add support for the game Sir Lancelot.

src/games/Roms.cpp, src/games/module.mk, src/games/supported/LostLuggage.cpp, src/games/supported/LostLuggage.hpp
The ROM file is `lostluggage.bin`, with the following information:
```
Cart Name:       Lost Luggage (1981) (Apollo)
Cart MD5:        7c00e7a205d3fda98eb20da7c9c50a55
```
The lives are handled slightly non-standard in this game: with one life (luggage icon in the bottom left) remaining the game ends if you miss a luggage piece.  Is there any guidance on how this should be handled?  (I can subtract 1 of course but the current commit just outputs the in-game display of lives.)
=> Add support for the game Lost Luggage.

src/games/supported/DonkeyKong.cpp
This fixes the wrong terminal condition.
I noticed however, that sometimes the `sharedLibraryInterfaceExample` application hangs on special events such as playing in-game sounds and game-over.
=> Fix terminal condition.

Readme.txt
I compile ALE infrequently enough that I always forget which method it uses and forget where to look. The twin compilation systems don't help.
I think adding this instructions to Readme.txt could help other people too. Might be worth adding them in README.md too, but that one points to the manual already. The manual is a little bit too much for people who just want to compile and play though, so it might still be worth it. 
Thoughts?
=> Quick and dirty compilation instructions

ale_python_interface/__init__.py, doc/examples/python_example.py, setup.py
Minimal updates required for python2/3 compatibility. I'm unhappy with having to append 'b' in front of strings when interacting with ale (e.g. ale.setInt(b'random_seed', 123)). Reason is because strings in python3 are unicode by default while ctypes expects a byte-encoded string (which used to be default in python 2.7). Adding the b prefix tells python3 to treat the string as bytes. Hopefully ctypes will be updated to play better with python3 unicode strings. Until then, I'm afraid we may be stuck with the b-prefixed strings. 
I've tested the PR on Ubuntu with python 2 and python 3. Both work fine, and pip install is working for both as well.
=> Updated ale_python_interface for python3.

ale_python_interface/ale_python_interface.py
This PR avoids the spurious imports (such as ale_lib in ale_python_interface.py) that can take place through `*`. The `__all__` [directive](https://docs.python.org/2/tutorial/modules.html#importing-from-a-package) allows us to only expose `ALEInterface`, which is the only object of interest to the user.
All of the following variants on `import` should work:
```
from ale_python_interface import ALEInterface
from ale_python_interface.ale_python_interface import ALEInterface
from ale_python_interface.ale_python_interface import *
print(ALEInterface)
print(ale_lib)
```
And result in :
```
$ python test.py 
<class 'ale_python_interface.ale_python_interface.ALEInterface'>
Traceback (most recent call last):
File "configdict.py", line 6, in <module>
print(ale_lib)
NameError: name 'ale_lib' is not …
```
=> Avoid spurious imports

src/games/supported/Pong.cpp
The game 'Pong' (really, 'Video Olympics') was missing the fire button as part of its set of minimal actions. This will affects backward reproducibility somewhat, but most algorithms shouldn't be too affected by this change.
=> Added missing minimal actions to Pong

.gitignore, README.md
In ALE master compiling the project generates a number of outputs, like the CMake build files and the `ale` binary itself, that can interfere with hacking on ALE and versioning changes.
For my work I decided to git ignore these generated files and use a build dir to keep the CMake files. This way I don't accidentally commit these generated outputs and I dont see the dirty status in my projects that include ALE. I thought I'd send a PR in case you think this is more convenient too.
Thanks for ALE!
=> Avoid build noise in versioning

src/ale_interface.cpp, src/common/ColourPalette.cpp
getScreenRGB was only sending the first third of pixels to the buffer because it did not multiply the screen size by the number of channels (3 in case of RGB). Fixed.
=> Fixed getScreenRGB, was not sending all three channels.

src/ale_interface.cpp, src/ale_interface.hpp, src/environment/stella_environment.cpp, src/environment/stella_environment.hpp
It came up when I was using ALEInterface in an old MDP class. Not very useful but it costs little effort.
Also removed unnecessary duplicate checks on ALEInterface::game_over
=> Make StellaEnvironment::isTerminal and ALEInterface::game_over const

ChangeLog, doc/manual/manual.tex, src/emucore/Settings.cxx
This turns off color averaging by default.
By default, and counter to the documentation, ALE blends frames together to make environment observations. I would like to argue that it is better to define an observation as a single frame by default as it more closely corresponds to the "true" emulator screen. This is the approach taken by deepmind/xitari for instance, and it might be nice to align settings in this case to help avoid fragmentation.
I was burned by this misdocumented default, rendering certain experiments less than perfectly comparable, so I'm sending this PR in case it is accepted and helps others avoid this issue.
I included a slight doc change and a changelog notice in case these are helpful and desired, but I could leave these out too if you prefer.
This is an opinionated …
=> Default color averaging to false, making observations single frames

ale_python_interface/ale_c_wrapper.h, ale_python_interface/ale_python_interface.py
By having this interface I'll be able to suppress the messages in Python by
```python
ALEInterface.setLoggerMode(ALEInterface.Logger.Warning)
```
=> add logger mode interface to python

src/games/Roms.cpp, src/games/module.mk, src/games/supported/Kaboom.cpp, src/games/supported/Kaboom.hpp
I figured out where and how [Kaboom!](https://en.wikipedia.org/wiki/Kaboom!_(video_game)) stores the score and the number of "lives" (buckets), with help from the Stella debugger and this disassembly: http://www.bjars.com/source/Kaboom.asm.
When the score reaches 999,999 points, the game freezes, so I used that as a terminal condition (in addition to the regular one in which you have no more lives left).
=> Add Kaboom! rom

CMakeLists.txt
In my usage of ALE I only ever need the C library for the Python interface. For convenience I separated the build targets so that it isn't necessary to compile whichever of the C++ library, C library, and ALE binary are unneeded in a particular use case.
p.s. This is my first attempt at a CMake patch so please double-check that its not in error. I'd be happy to correct it if needed.
=> Separate build targets for the libraries and binary

src/ale_interface.cpp, src/ale_interface.hpp
I've isolated my changes to just those that will add the warning message for unsupported ROMs, hopefully for clarity.
=> Add minimally invasive code that checks ROMs against known md5s

src/ale_interface.hpp, src/environment/ale_state.cpp, src/environment/ale_state.hpp, src/games/RomUtils.cpp, src/games/RomUtils.hpp
The last set of functionalities I need before actually implementing the mode and difficulty changes are the abilities to:
- deal with other events supported in Stella but not previously supported in the ALE (Setting difficulty level and pressing select).
- write to RAM so I can set the game mode.
I believe my next PR, after these two features, will finalize the implementation of the desired functionalities (stella_environment and RomSettings). Then it will be a matter of updating the code in all games.
=> Accessing other events inside Stella and allowing ALE to change RAM values

src/games/supported/Alien.cpp, src/games/supported/Alien.hpp, src/games/supported/Amidar.cpp, src/games/supported/Amidar.hpp, src/games/supported/BeamRider.cpp, src/games/supported/BeamRider.hpp, src/games/supported/ChopperCommand.cpp, src/games/supported/ChopperCommand.hpp, src/games/supported/DemonAttack.cpp, src/games/supported/DemonAttack.hpp, src/games/supported/Freeway.cpp, src/games/supported/Freeway.hpp, src/games/supported/Frostbite.cpp, src/games/supported/Frostbite.hpp, src/games/supported/JamesBond.cpp, src/games/supported/JamesBond.hpp, src/games/supported/JourneyEscape.cpp, src/games/supported/JourneyEscape.hpp, src/games/supported/QBert.cpp, src/games/supported/QBert.hpp, src/games/supported/RiverRaid.cpp, src/games/supported/RiverRaid.hpp, src/games/supported/Seaquest.cpp, src/games/supported/Seaquest.hpp, src/games/supported/Zaxxon.cpp, src/games/supported/Zaxxon.hpp
In order to submit small PRs I'm changing just 12 games for now. I'll keep working on the others. A summary of the current status is below. I won't deal with 2-player modes.
- **Games in which mode and difficulty switch are already implemented:**
`Alien`, `Amidar`, `BeamRider`, `ChopperCommand`, `DemonAttack`, `Freeway`, `Frostbite`, `Jamesbond`, `JourneyEscape`, `QBert`, `RiverRaid`, `Seaquest`.
- **Games in which mode and difficulty switch are not implemented yet:**
`Adventure`, `AirRaid`, `Asteroids`, `Atlantis`, `BankHeist`, `BattleZone`, `Berzerk`, `Bowling`, `Boxing`, `Breakout`, `Centipede`, `CrazyClimber`, `Defender`, `DoubleDunk`, `FishingDerby`, `Frogger`, `Galaxian`, `Gopher`, `Gravitar`, `Hero`, `IceHockey`, `Kaboom`, `Kangaroo`, `KingKong`, `Koolaid`, `LostLuggage`, `MrDo`, …
=> Mode and difficulty switch in 12 games

CMakeLists.txt, doc/examples/Makefile.sharedLibraryWithModes
The new name was not being ignored but git, because of its name. Also the clean rule wasn't updated correctly. Since there's no problem with the previous name, I'm just changing it back.
=> Reverting name of examples about modes

src/environment/stella_environment.cpp
Fixes the following bug:
When `repeat_action_prob > 0`, `StellaEnvironment::act` will repeat the last played actions. These are not reset when the environment is reset, so the first action on a new episode may be a repeat of the last action of the previous episode.
This is patched by resetting the last actions to be NOOPs whenever the environment is reset (when the episode ends), consistent with the constructor.
=> Reset actions on reset

src/emucore/Console.cxx, src/emucore/m6502/src/System.cxx, src/emucore/m6502/src/System.hxx
Eliminate variables which are constant.
Inline memory access methods.
Benchmarking shows avg. ~30% speedup on multiple Atari games.
=> Optimize Atari emulator by ~30%

src/environment/ale_state.cpp, src/environment/ale_state.hpp, src/environment/stella_environment.cpp
Previously, the values were hardcoded macros. Those are retained as
the default value, but the effective values may now be set
programmatically.
This changes the serialization format (the paddle values now appear as
the last two values).
=> [ale_state] Makes "paddle min/max" configurable.

.travis.yml
Travis only provides two cores, so it is not useful to run make with
more than two jobs.
=> [travis] Build examples, reduce number of jobs, update distro.

CMakeLists.txt, src/games/RomSettings.hpp
This is the first PR in a set of PRs merging [openai/atari-py](https://github.com/openai/atari-py) into the ALE. This first PR adds the ability to build the ALE on Windows.
To get a proper build on Windows we had to:
1. Add zlib to the repository. This is how Stella now deals with zlib as well ([stella/src/zlib](https://github.com/stella-emu/stella/tree/master/src/zlib)).
2. CMake changes: Hide some flags under a GCC check, export all Windows symbols, and link zlib properly.
For all these PRs I'm hoping @christopherhesse will be able to review them before @mgbellemare takes a look.
=> atari-py 1/3: Windows build

src/ale_interface.cpp, src/ale_interface.hpp
Give useful feedback if we can't valid a valid ROM wrapper. Hopefully, this will prevent issues like #292.
I just refactored `checkForUnsupportedRom` into `isSupportedRom` so we can give some useful feedback if the ROM isn't supported and we failed to find a wrapper.
=> User feedback if we can't find a valid wrapper

src/games/RomSettings.cpp, src/games/RomSettings.hpp, src/games/RomUtils.cpp, src/games/RomUtils.hpp
Two commits in this PR:
* one to read a byte of memory from anywhere (not just from [0, 1024) as the existing facility provides)
* one to check whether a game mode is valid
(Please don't squash, but rebase-merge)
=> Two new features: read memory, check game mode validity

src/emucore/TIA.cxx
The initializing functions are now guarded with std::call_once.
It is someone annoying that we are computing these values at runtime
even though they are perfectly well deterimined statically. However,
the programmatic expressions may be more meaningful than the raw
numbers, so it is useful to retain the code. We _could_ make the code
evaluate as constant expressions, but unfortunately this seems to
require non-standard toolchain settings to allow for a rather large
constant evaluation budget during compilation.
The upstream Stella code has diverged from this code anyway, so this
is just a local fix for the time being.
=> [emucore/TIA.cxx] Make initialization of static data thread-safe.

src/emucore/Cart.cxx, src/emucore/Cart.hxx, src/emucore/Cart3E.cxx, src/emucore/Cart3E.hxx, src/emucore/CartAR.cxx, src/emucore/CartAR.hxx, src/emucore/CartCV.cxx, src/emucore/CartCV.hxx, src/emucore/CartE7.cxx, src/emucore/CartE7.hxx, src/emucore/CartF4SC.cxx, src/emucore/CartF4SC.hxx, src/emucore/CartF6SC.cxx, src/emucore/CartF6SC.hxx, src/emucore/CartF8SC.cxx, src/emucore/CartF8SC.hxx, src/emucore/CartFASC.cxx, src/emucore/CartFASC.hxx, src/emucore/CartMC.cxx, src/emucore/CartMC.hxx, src/emucore/OSystem.cxx, src/emucore/Random.cxx, src/emucore/Random.hxx
Instead, forward the OSystem's RNG to each cartridge constructor that
needs randomess (to initialize memory).
This makes the system more deterministic.
=> [emucore, Cart*] Delete old, process-global RNG instance.

src/emucore/Cart.cxx, src/emucore/Cart.hxx
Previously, it was a static variable, which is difficult to use in complex situations.
=> [emucore/Cart] Make "about string" part of the state

src/ale_interface.cpp, src/main.cpp
The state of I/O buffering is global and should not be modified
arbitrarily from within a library. Rather, it should be set only by
the entry point.
=> [ale_interface, main] Move I/O buffer handling to main

src/ale_interface.cpp
Previously, ROM-modified settings could only affect a subset of keys,
since the emulator was already set up before the modifications were
even applied (by way of ALEInterface::loadRom).
=> [ale_interface] Delay loadSettings until after modifications

src/ale_interface.hpp, src/environment/stella_environment.hpp
This change adds observer functions to StellaEnvironment and
ALEInterface to retrieve the current "difficulty" and "mode"
settings. Previously, these values could be set, but not queried.
=> [ale_interface, stella_environment] Expose difficulty and mode

ale_py/ale_c_wrapper.h, src/environment/ale_ram.hpp
Fixes const correctness, removes user-defined special members (the
implied definitions already copy and assign arrays); replaces a macro
with a member constant.
=> [ale_ram] Simplify and clean up

src/emucore/OSystem.cxx
Previously, those were leaked when their only reference was
overwritten as part of reloading the ROM.
=> [emucore/OSystem.cxx] Delete dynamically allocated objects

src/ale_interface.cpp
The call was moved unconditionally by 3bee0b6a74491ab1c0120d05c94b1a2b0c5d9958,
which left the Console (and its properties) uninitialized on
the error path "wrapper == NULL". This change reinstates that
call locally only on this path, which ends in program exit.
=> [ale_interface] Reinstate a call to loadSettings on error path

src/ale_interface.cpp, src/ale_interface.hpp
The default argument was not used and not useful in the .cpp file;
it is reasonable and useful in the interface.
The relevant documentation is also moved.
=> [ale_interface] Move default argument to the public declaration

src/emucore/Cart.cxx, src/emucore/OSystem.cxx
* Cartridge::create did not check whether a catridge had been created
before using it (introduced by 2121bf7be7503d66a1b6cd58f952d6e81b0b1d91).
* Cartridge::autodetectType did not check that the "AR" cartridge ROM
had non-zero size.
* Cartridge::autodetectType did not check that the fallback choice of
"4K" cartridge had the correct ROM size. Since the size-checked case
is already handled earlier, we remove the entire fallback case.
* Cartridge::searchForBytes did not check whether the search term was
within the bounds of the search range.
* OSystem::createConsole and OSystem::getROMInfo failed to deallocate
the image memory in case of a cartridge loading error.
Note that this change does not provide complete checking for ROM
validity: if the conditional block at Cart.cxx:79 is skipped, no …
=> [emucore/{OSystem,Cart}.cxx] Fix several bugs in handing invalid ROMs.

src/common/SoundExporter.hpp, src/games/supported/MiniatureGolf.hpp
This doesn't make a difference in C++11, but provides a inline
definition in C++17 (as per
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2.pdf).
At present, no definition is provided, so those members cannot be ODR-used.
=> [SoundExporter.hpp, games/MiniatureGolf.hpp] Use "constexpr" for static class member integral constants.

src/games/supported/Othello.cpp, src/games/supported/Othello.hpp
The othello game relies on cursor flickering to decide if the game is over. Unfortunately, the cursor also stops flickering  if you just hold down the fire button (repeatedly take action 1). Then the game thinks it has terminated after just a few steps. This example can demonstrate this behavior:
```python
import  ale_py
ale = ale_py.ALEInterface()
ale.loadROM("Arcade-Learning-Environment/roms/othello.bin")
ale.reset_game()
game_len = 0
while not ale.game_over():
rew = ale.act(1)
game_len += 1
print(game_len)
```
This patch changes the code to instead look at the player indicator (memory location 0xc0) is 0 for a number of steps. This fixes the above issue, and I have manually tested that this correctly terminates the game after no more moves can be made.
=> fixed othello terminate-if-fire issue

src/ale_interface.cpp, src/ale_interface.hpp
The non-copying version is useful for Python bindings in other projects, since it allows viewing the emulator's internal storage without requiring the caller to manage the storage.
=> [ale_interface] Separate "getString" into copying and non-copying versions.

src/games/supported/BasicMath.cpp, src/games/supported/FlagCapture.cpp, src/games/supported/MarioBros.cpp, src/games/supported/SpaceWar.cpp, src/games/supported/VideoCheckers.cpp
This change undoes a previous "hack" that was needed in order to allow "0" to be a valid game mode. After d3f2b258ed4890a8e10a6ff876436f585d6e6cef, this is no longer required, so this change restores the "original" game mode numbering.
This affects BasicMath, FlagCapture, MarioBors, SpaceWars, and VideoCheckers.
=> [games] Renumber game modes.

.github/workflows/build-ale.yml, CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
This PR includes:
- subproject compiler options instead of target based options. This will stop the propagation of compiler options through `_INTERFACE`
- updates to the test framework to use CTest in preparation of C++ tests.
- CI Python bump to 3.9, installing cmake via pip for multiplatform consistency, and pybind11 bump to 2.6.1
=> CMake refinement

pyproject.toml, setup.cfg, setup.py
We now use setup.cfg for all static metadata and setup.py for dynamically building the library and specifying the version string. This also uses Ninja when available as we can specify ninja as a build-dependency in pyproject.toml.
The general outline of setup.py follows the excellent pybind11 cmake example project.
=> Python setuptools refactor

src/common/SoundNull.cxx, src/common/SoundSDL.cxx, src/emucore/OSystem.cxx, src/emucore/Settings.cxx
There were some internal settings leftover from Stella. These are unused and can be removed along with their corresponding side-effects (e.g., `showinfo`, we use Logger).
=> Remove leftover settings

src/emucore/Console.cxx, src/emucore/Console.hxx, src/emucore/Event.hxx
We can remove the `Fry` event as it was unused in the ALE.
=> Remove unused `Event` types

src/emucore/Console.cxx, src/emucore/Console.hxx
* Remove user-defined palette, we no longer allow specifying user-defined palette
* Remove cart() riot() methods, these were meant for the debugger.
* toggleFormat() togglePalette() togglePhosphor() were all meant for interactive toggling. We don't need this.
* initializeVideo() initializeAudio() this was meant for the Stella GUI, we don't use it.
* changeYStart(int) changeHeight(int), these were meant for interactively modifying the height and Y-start position of the screen. For our purposes these are fixed in the ROM properties, these methods were interactive.
* toggleTIABit(...) and specific bit functions, these were meant for interactively debugging the TIA, the ALE doesn't use any of these.
=> Refactor `Console` to remove unused methods

src/emucore/OSystem.cxx, src/emucore/OSystem.hxx
* getROMInfo(...) was used by the Stella CLI, we don't use this method.
* propSet() was used by the Stella CLI & GUI, we don't use this method.
* kNumUIPalettes was used in the Stella GUI UI palette
=> Refactor `OSystem` to remove unused methods

src/common/SoundNull.cxx, src/common/SoundNull.hxx, src/common/SoundSDL.cxx, src/common/SoundSDL.hxx, src/emucore/Console.hxx, src/emucore/OSystem.cxx, src/emucore/Sound.hxx
We should only require what we use as a parameter. We don't require `OSystem` for anything other than `Settings`.
=> `Sound*` only requires access to `Settings` not `OSystem`

src/emucore/OSystem.cxx
This causes a build failure for me when building without SDL support.
=> Add a missing std namespace qualifier

src/ale_interface.cpp, src/ale_interface.hpp
As the title says, this patch add missing const correctness to getters of the `ALEInterface` class.
=> Add `const` keyword to getters

src/python/env/gym.py
This PR addresses https://github.com/mgbellemare/Arcade-Learning-Environment/issues/471 and https://github.com/mgbellemare/Arcade-Learning-Environment/issues/475 by adding the property render_mode to AtariEnv.
Quick test:
```python
import gym
from gym.wrappers import RecordVideo
env = RecordVideo(
gym.make('ALE/Breakout-v5', render_mode="rgb_array"),
video_folder='video'
)
env.reset()
for _ in range(100):
env.step(env.action_space.sample())
env.close()
```
@JesseFarebro
=> FIX: add render_mode attribute

src/common/ColourPalette.hpp, src/common/SoundExporter.hpp, src/emucore/MD5.hxx, src/emucore/Props.cxx, src/emucore/PropsSet.hxx, src/emucore/Sound.hxx, src/emucore/Switches.cxx, src/emucore/Switches.hxx
=> Add missing imports for cstdint

src/emucore/TIASnd.hxx
This include is necessary for the project to compile with GCC 13.
See https://gcc.gnu.org/gcc-13/porting_to.html
Fixes #502
=> build: fix compilation with gcc 13

.github/docker/manylinux-vcpkg.Dockerfile, .github/workflows/ci.yml, .github/workflows/pypi.yml
Dependabot couldn't update `actions/download-artifact` and `actions/upload-artifact` v4 at the same time as they need to be updated at the same time according to the release notes
=> Bump `actions/download-artifact` and `actions/upload-artifact` v4

.pre-commit-config.yaml, docs/environments.md, setup.py, src/ale/python/__init__.py, src/ale/python/__init__.pyi, src/ale/python/env.py, src/ale/python/registration.py, src/ale/python/roms/__init__.py, tests/python/test_atari_env.py, tests/python/test_python_interface.py, tests/python/utils.py
This PR fixes several issues
* Add pydocstyle to pre-commit
* `get_keys_to_action` had `None` for no-op however for `gymnasium.utils.play.play` this is not allowed, therefore, this is updated to use `e` for no-op (https://github.com/Farama-Foundation/Arcade-Learning-Environment/issues/557)
* The environment frameskip for v5 specified it was 5 however it was actually 4
=> Add pydocstyle to pre-commit, fix `get_keys_to_action` and environment frameskip

README.md
This PR fixes a typo in the Quickstart of README.md. 
If one follows the README.md example below in Linux:
```python
from ale_py import ALEInterface, roms
ale = ALEInterface()
x = roms.get_rom_path("Breakout")
ale.loadROM(x)
ale.reset_game()
reward = ale.act(0)  # noop
screen_obs = ale.getScreenRGB()
```
you get `UserWarning: Rom Breakout not supported.` and `get_rom_path` returns `None` and then
```
TypeError: loadROM(): incompatible function arguments. The following argument types are supported:
1. (self: ale_py._ale_py.ALEInterface, arg0: str) -> None
2. (self: ale_py._ale_py.ALEInterface, arg0: os.PathLike) -> None
```
The issue is the file search is case sensitive. To fix, just run the same with `breakout` instead of `Breakout`.
=> Fix main page example 'Breakout' to 'breakout'

README.md, docs/environments.md
Adding instructions for how to use CALE (Continuous ALE), as well as citation instructions.
Will also add instructions to https://ale.farama.org/environments/.
=> Add CALE instructions and citation to README

.github/workflows/ci.yml, pyproject.toml, setup.py
Instead of depending on `cmake` and `ninja` executables unconditionally, add these dependencies only if system executables are not available. This ensures that system CMake is used when available (instead of being overridden by the PyPI build of CMake), so the user can benefit from improved portability due to downstream patching and avoids unnecessary dependencies.
This also adjusts the generator choice to support system `ninja` install, i.e. one without a `ninja` module.
=> Use system CMake if available

src/ale/vector/preprocessed_env.hpp, tests/python/test_atari_vector_env.py
The `preprocessing_env.hpp` incorrectly doesn't seed the environment if the value is equal to zero. 
This PR fixes the bug and allows the vector environment to be deterministic with tests
=> Fix vector env determinism

src/ale/python/env.py, tests/python/test_atari_env.py
https://github.com/Farama-Foundation/Gymnasium/pull/1384
AtariEnv implements the `get_keys_to_action` with the wrong types
This PR updates it to use a strings for keys to make it easier to debug and int for actions
=> Change `get_keys_to_action` from `dict[ale_py.Action, tuple[int, ...]` to `dict[str, tuple[int, ...]]`

src/ale/python/ale_vector_xla_interface.cpp, src/ale/python/env.py, src/ale/python/vector_env.py, src/ale/vector/preprocessed_env.hpp, tests/python/test_atari_vector_env.py
The `AtariVectorEnv` continuous action implementation was horribly wrong and wasn't noticed as there wasn't tests. 
This PR fixes the implementation and adds tests for it
=> Fix vector continuous actions implementation

src/ale/vector/preprocessed_env.hpp, tests/python/test_atari_vector_env.py
These variables mean
* `episodic_life` - included in `AtariPreprocessing` will cause the environment to reset when a life is lost
* `life_loss_info` - Normally used in 100k Atari will return a terminated=True signal when a life is lost but not reset the environment to allow the agent to explore further. Its critical to note if this parameter is used as it has a significant impact on training
These were implemented however without testing
=> Add tests on vector `episodic_life` and `life_loss_info`

src/ale/python/vector_env.py, src/ale/vector/async_vectorizer.hpp, src/ale/vector/utils.hpp, tests/python/test_atari_vector_env.py
In the vector env, users have the option to specify a batch size thats different from the number of environments. 
If used, then rather than waiting for all sub-environments to return a result, this allows the first N results to be returned causing a significant speed up however is significantly more complex to use in training
=> Add vector async tests

src/ale/python/ale_vector_xla_interface.cpp, src/ale/python/env.py, src/ale/python/vector_env.py, src/ale/vector/async_vectorizer.hpp, src/ale/vector/preprocessed_env.hpp, tests/python/test_atari_env.py, tests/python/test_atari_vector_env.py
Currently the vector environment testing is done with a single rom, Breakout, for speed as otherwise the testing would take hours. 
However, to make it easier to test if developers wish, the tests are now in a class that can be parametrized by all available ROMs. 
In doing this, bugs were found
* Fixes variable screen sizes for some environments
* Some environments have no lives causing `test_episodic_life_and_life_loss_info` to error
=> Environment parametrize vector testing

src/ale/vector/preprocessed_env.hpp
With the bugs fixed, I now have the joy of optimising the implementation.
Previously, a `std::deque` was used and for each frame, it was popped then new memory allocated for the frame. 
This PR optimises the frame stacking to have a single array of contiguous memory that acts like a circular / ring buffer such that we just overwrite the old frame with the new frame and write the frames oldest to newest
| num-envs | main steps per second | PR steps per second | 
| --- | --- | --- | 
| 16 | 11300 | 11346 |
| 64 | 14100 | 15168 | 
| 128 | 16750 | 17311 |
=> Optimising frame stack with contiguous memory

src/ale/vector/async_vectorizer.hpp, src/ale/vector/utils.hpp, tests/python/test_atari_vector_env.py
This PR optimises the `StateBufferQueue` to allow multiple threads to write Timesteps at the same time while using Semaphore that are more efficient than mutexes. 
| num-envs | main steps per second | PR steps per second | 
| --- | --- | --- | 
| 16 | 11346 | 11272 |
| 64 | 15168 |  15044 |
| 128 | 17311 |  17349 |
=> Optimise `StateBufferQueue` to use Semaphore not mutexes
